name: Deploy to Phone

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add known hosts
      run: echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

    - name: Copy files to phone
      run: scp -P 8080 -r . jb@stampit.ddns.net:~/stampit

    - name: Execute deployment script
      run: ssh -p 8080 jb@stampit.ddns.net "cd ~/stampit && ./deploy.sh"
